title: Î»ausek
author: lausek
description: "Adventures of a Software Engineer"
keywords: "lausek, sap, abap, laurin, kirbach, lpk"

collections:
    tagged:
        output: true
    extra:
        output: true

highlighter: rouge
sass:
    style: compressed
