title: Î»ausek
author: lausek
description: "This is my little blog about programming - mainly in ABAP - and other computer stuff."
keywords: "lausek, sap, abap, laurin, kirbach, lpk"

collections:
    tagged:
        output: true
    extra:
        output: true

highlighter: rouge
sass:
    style: compressed
